Fix needed to fix this error with Windows build. See http://stackoverflow.com/questions/1439621/problem-with-loading-win32file-pyd-on-python-2-6
Traceback (most recent call last):
  File "run_p2pool.py", line 3, in <module>
    from p2pool import main
  File "zipextimporter.pyc", line 82, in load_module
  File "p2pool\main.pyc", line 22, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "p2pool\bitcoin\worker_interface.pyc", line 12, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "p2pool\util\jsonrpc.pyc", line 8, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "twisted\web\client.pyc", line 21, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "twisted\internet\endpoints.pyc", line 28, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "twisted\internet\stdio.pyc", line 28, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "twisted\internet\_win32stdio.pyc", line 15, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "twisted\internet\_pollingfile.pyc", line 102, in <module>
  File "zipextimporter.pyc", line 98, in load_module
ImportError: MemoryLoadLibrary failed loading win32file.pyd